---
- block:
    - include: context.yml

    - include: accounts.yml
      vars: {
        accounts_groups: "{{ gitlab_ce_groups|d([]) }}",
        accounts_users: "{{ gitlab_ce_users|d([]) }}"
      }

    - include: workspace.yml

    - include: install.yml

    - include: setup.yml

  when: want_gitlab_ce

- name: "set has_gitlab_ce to {{ want_gitlab_ce }}"
  set_fact:
    has_dns: "{{ want_gitlab_ce }}"
