---


- name: setup daemontools for jenkins
  block:
    - name: create service directory
      file:
        path: "{{ gitlab_ce_daemontools_dir }}/{{ item }}"
        owner: root
        group: "{{ root_group }}"
        mode: "0755"
        state: directory
      loop: "{{ gitlab_ce_daemontools_services }}"

    - name: create service log directory
      file:
        path: "{{ gitlab_ce_daemontools_dir }}/{{ item }}/log"
        owner: root
        group: "{{ root_group }}"
        mode: "0755"
        state: directory
      loop: "{{ gitlab_ce_daemontools_services }}"

    - name: create service log main directory
      file:
        path: "{{ gitlab_ce_daemontools_dir }}/{{ item }}/log/main"
        owner: "{{ daemontools_logger_user }}"
        group: "{{ root_group }}"
        mode: "0755"
        state: directory
      loop: "{{ gitlab_ce_daemontools_services }}"

    - name: deploy service run script
      template:
        src: "svscan/{{ item }}/run"
        dest: "{{ gitlab_ce_daemontools_dir }}/{{ item }}/run"
        owner: root
        group: "{{ root_group }}"
        mode: "0755"
      loop:  "{{ gitlab_ce_daemontools_services }}"

    - name: deploy service log run script
      template:
        src: "svscan/{{ item }}/log/run"
        dest: "{{ gitlab_ce_daemontools_dir }}/{{ item }}/log/run"
        owner: root
        group: "{{ root_group }}"
        mode: "0755"
      loop:  "{{ gitlab_ce_daemontools_services }}"

    - name: link daemontools
      file:
        src: "{{ gitlab_ce_daemontools_dir }}/{{ item }}"
        dest: "{{ daemontools_svscan_dir }}/{{ item }}"
        state: link
      loop: "{{ gitlab_ce_daemontools_services }}"

  when: has_daemontools|d(false)



- name: start standard service
  block:
    - name: enable standard FreeBSD service
      include: sysrc.yml key="{{ item.key }}" value="{{ item.value }}"
      loop: "{{ gitlab_ce_sysrcs }}"
      when: ansible_system == 'FreeBSD'

    - name: enable standard Linux service
      service:
        name: "{{ item }}"
        enabled: true
      loop: "{{ gitlab_ce_services }}"
      when: ansible_system == 'Linux'

    - service:
        name: "{{ item }}"
        state: started
      loop: "{{ gitlab_ce_services }}"
      register: t_jenkins_service

    - service:
        name: "{{ item }}"
        state: restarted
      loop: "{{ gitlab_ce_services }}"
      when: t_gitlab_ce_conf.changed and not t_gitlab_ce_service.changed

  when: not (has_runit|d(false) or has_daemontools|d(false))
