---


- name: setup daemontools for jenkins
  block:
    - name: create service directory tree
      file:
        path: "{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
        state: directory
      loop: "{{ gitlab_ce_daemontools_directories }}"

    - template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: "{{ root_group }}"
        mode: "{{ item.mode }}"
      loop:
        - { src: svscan/gitlab/run, dest: "{{ gitlab_ce_daemontools_gitlab_dir }}/run", mode: "0755" }
        - { src: svscan/gitlab/log/run, dest: "{{ gitlab_ce_daemontools_gitlab_log_dir }}/run", mode: "0755" }
        - { src: svscan/gitlab_pages/run, dest: "{{ gitlab_ce_daemontools_gitlab_pages_dir }}/run", mode: "0755" }
        - { src: svscan/gitlab_pages/log/run, dest: "{{ gitlab_ce_daemontools_gitlab_pages_log_dir }}/run", mode: "0755" }

    - name: link daemontools
      file:
        src: "{{ item.src }}"
        dest: "{{ daemontools_svscan_dir }}/{{ item.dest }}"
        state: link
      loop:
        - { src: "{{ gitlab_ce_daemontools_gitlab_dir }}", dest: gitlab }
        - { src: "{{ gitlab_ce_daemontools_gitlab_pages_dir }}", dest: gitlab_pages }

  when: has_daemontools|d(false)



- name: start standard service
  fail:
    msg: "not implemented"
#   block:
#     - name: enable standard FreeBSD service
#       include: sysrc.yml key="{{ item.key }}" value="{{ item.value }}"
#       loop: "{{ jenkins_services_sysrcs }}"
#       when: ansible_system == 'FreeBSD'

#     - name: enable standard Linux service
#       service:
#         name: "{{ item }}"
#         enabled: true
#       loop: "{{ jenkins_services }}"
#       when: ansible_system == 'Linux'

#     - service:
#         name: "{{ item }}"
#         state: started
#       loop: "{{ jenkins_services }}"
#       register: t_jenkins_service

#     - service:
#         name: "{{ item }}"
#         state: restarted
#       loop: "{{ jenkins_services }}"
#       when: t_jenkins_conf.changed and not t_jenkins_service.changed

  when: not (has_runit|d(false) or has_daemontools|d(false))
