---

gitlab_ce_dir: "{{ services_dir }}/gitlab-ce"
gitlab_ce_git_home: "{{ gitlab_ce_dir }}/git"
gitlab_ce_gitlab_pages_home: "{{ gitlab_ce_dir }}/gitlab-pages"
gitlab_ce_etc: "{{ gitlab_ce_dir }}/etc"
gitlab_ce_ssl_dir: "{{ gitlab_ce_etc }}/ssl"

gitlab_ce_directories:
    - { path: "{{ gitlab_ce_dir }}", owner: root, group: 0, mode: "0755" }
    - { path: "{{ gitlab_ce_git_home }}", owner: "{{ gitlab_ce_git_user }}", group: "{{ gitlab_ce_git_group }}", mode: "0700" }
    - { path: "{{ gitlab_ce_gitlab_pages_home }}", owner: "{{ gitlab_ce_gitlab_pages_user }}", group: "{{ gitlab_ce_gitlab_pages_group }}", mode: "0700" }
    - { path: "{{ gitlab_ce_etc }}", owner: root, group: "{{ gitlab_ce_git_group }}", mode: "0750" }
    - { path: "{{ gitlab_ce_ssl_dir }}", owner: root, group: "{{ gitlab_ce_git_group }}", mode: "0750" }
