#!/bin/sh

exec 2>&1

export PATH="/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin"

RAILS_ENV="production"
APP_ROOT="{{ gitlab_ce_application_dir }}"
SIDEKIQ_USER="{{ gitlab_ce_git_user }}"
SIDEKIQ_CONF="$APP_ROOT/config/sidekiq_queues.yml"

set -e

cd "$APP_ROOT"

exec setuidgid "$SIDEKIQ_USER" \
     pgrphack \
     bundle exec \
     sidekiq -C "SIDEKIQ_CONF" -e "$RAILS_ENV"
